// Registrar el código ASME BPVC.V-2023 si no existe
if (!getCode('ASMEV')) {
    console.error('El código ASME BPVC.V-2023 no está registrado. Registrándolo ahora...');
    registerCode('ASMEV', {
        title: "ASME Boiler and Pressure Vessel Code Section V - Nondestructive Examination",
        titleEs: "Código de Calderas y Recipientes a Presión ASME Sección V - Examen No Destructor"
    });
}

// Registrar el capítulo 1
registerChapter('ASMEV', {
    id: 1,
    title: "General Requirements",
    titleEs: "Requisitos Generales",
    content: `<h3>ARTICLE 1 GENERAL REQUIREMENTS</h3>
    <div class="subsection">
        <h4>T-110 SCOPE</h4>
        <p>(a) This Section of the Code contains requirements, methods, and techniques for nondestructive examination (NDE), which are Code requirements to the extent that they are specifically referenced and required by other Code Sections or referencing documents. These NDE methods are intended to detect surface and internal imperfections in materials, welds, fabricated parts, and components. Nonmandatory Appendix A of this Article provides a listing of common imperfections and damage mechanisms, and the NDE methods that are generally capable of detecting them.</p>
        <p>(b) For general terms such as inspection, flaw, discontinuity, evaluation, etc., refer to Mandatory Appendix I.</p>
        <p>(c) New editions of Section V may be used beginning with the date of issuance and become mandatory 6 months after the date of issuance unless modified by the referencing document.</p>
        <p>(d) Code Cases are permissible and may be used, beginning with the date of approval by ASME. Only Code Cases that are specifically identified as being applicable to this Section may be used. At the time a Code Case is applied, only the latest revision may be used. Code Cases that have been incorporated into this Section or have been annulled shall not be used, unless permitted by the referencing Code. Qualifications using the provisions of a Code Case remain valid after the Code Case is annulled. The Code Case number shall be listed on the NDE Procedure or Personnel Certification, as applicable.</p>
    </div>
    <div class="subsection">
        <h4>T-120 GENERAL</h4>
        <p>(a) Subsection A describes the methods of nondestructive examination to be used if referenced by other Code Sections or referencing documents.</p>
        <p>(b) Subsection B lists Standards covering nondestructive examination methods which have been accepted as standards. These standards are not mandatory unless specifically referenced in whole or in part in Subsection A or as indicated in other Code Sections or referencing documents. Where there is a conflict between Subsection A and Subsection B, the requirements of Subsection A take precedence.</p>
        <p>(c) Any reference to a paragraph of any Article in Subsection A of this Section includes all of the applicable rules in the paragraph. In every case, reference to a paragraph includes all the subparagraphs and subdivisions under that paragraph.</p>
        <p>NOTE: For example, a reference to T-270 includes all of the rules contained in T-271 through T-277.3.</p>
        <p>(d) Reference to a standard contained in Subsection B is mandatory only to the extent specified.</p>
        <p>NOTE: For example, T-233 requires that Image Quality Indicators be manufactured and identified in accordance with the requirements or alternatives allowed in SE-747 or SE-1025, and Appendices, as appropriate for the style of IQI to be used. These are the only parts of either SE-747 or SE-1025 that are mandatory in Article 2. In many cases, Subsection B documents are not mandatory and are intended only for guidance or reference use.</p>
        <p>(e) For those documents that directly reference this Article for the qualification of NDE personnel, the qualification shall be in accordance with their employer's written practice. This written practice shall address the methods and techniques that are applicable to the organization's operations and shall be in accordance with one of the following documents:</p>
        <p>(1) SNT-TC-1A (2020 Edition),<sup>1</sup> Personnel Qualification and Certification in Nondestructive Testing, with the following exceptions:</p>
        <p>(-a) SNT-TC-1A (2020 Edition) shall not be considered a recommended practice but rather shall provide mandatory requirements. The verb "shall" is to be used in place of "should" when establishing minimum requirements of the written practice.</p>
        <p>(-b) The provisions of para. 1.5 are not applicable to specific and practical examinations [see (f) for rules relating to central certification programs].</p>
        <p>(-c) Machine problems are specific to vibration analysis and are not applicable to NDE practical examinations.</p>
        <p>(-d) The technical performance evaluation described in para. 10.2 shall be mandatory prior to recertification of Level I and Level II personnel.</p>
        <p>(-e) In addition to the examination requirements of para. 8.7, NDT Level III personnel shall be required to prepare a written procedure for each applicable method, meeting the requirements of an ASME construction or related inservice inspection code or standard before initial certification by each employer. For currently certified individuals, the procedure requirement shall be fulfilled at the next recertification event. Evaluation of the procedure shall be performed using a written checklist that addresses items relating to the technical and practical adequacy of the NDE procedure. A minimum passing grade of 80% is required. Evaluation of the procedure shall be performed by the NDT Level III responsible for the applicable method and so recorded.</p>
        <p>(-1) If the NDT Level III candidate will be required to administer practical examinations for certification or to perform examinations, interpretations, or evaluations to an ASME code or standard, the candidate shall complete the practical examinations required for a Level II in each applicable technique within the method with their current employer.</p>
        <p>(-2) The composite grade for NDT Level III personnel shall be determined by simple averaging of each required examination, including the written procedure and practical exam, as applicable, and so recorded. A composite grade of at least 80% is required.</p>
        <p>(-3) The NDT Level III candidate shall complete the requirements of (-e) only once for the current employer. The NDT Level III personnel are not required to complete the requirements of (-e) for recertification.</p>
        <p>(2) ANSI/ASNT CP-189 (2020 Edition),<sup>1</sup> ASNT Standard for Qualification and Certification of Nondestructive Testing Personnel, except that the provisions of para. 1.5 are not applicable to specific and practical examinations [see (f) for rules relating to central certification programs].</p>
        <p>(f) National or international central certification programs, such as ISO 9712–based programs, may alternatively be used to fulfill the written practice requirements of (e) for training, experience, general examination, basic examination, and method examination, as applicable.</p>
        <p>(g) In addition to the requirements described in (e) or (f) above, if the techniques of computed radiography (CR), digital radiography (DR), phased-array ultrasonic (PAUT), ultrasonic time-of-flight diffraction (TOFD), or ultrasonic full matrix capture (FMC) are to be used, the training, experience, and examination requirements found in Article 1, Mandatory Appendix II shall also be included in the employer's written practice for each technique as applicable.</p>
        <p>(h) Alternatively, performance-based qualification programs, in accordance with ASME ANDE-1-2020, ASME Nondestructive Examination and Quality Control Central Qualification and Certification Program, may be used for training, experience, examination, and certification activities as specified in the written practice.</p>
        <p>(i) When the referencing Code Section does not specify qualifications or does not reference directly Article 1 of this Section, qualification may simply involve a demonstration to show that the personnel performing the nondestructive examinations are competent to do so in accordance with the organization's established procedures.</p>
        <p>(j) The user of this Article is responsible for the qualification and certification of NDE personnel in accordance with the requirements of this Article. The organization's<sup>2</sup> Quality Program shall stipulate how this is to be accomplished. Qualifications in accordance with a prior edition of this Section are valid until recertification. Recertification or new certification shall be in accordance with the current edition of this Section. When any of the techniques included in (g) above are used, the additional requirements of that paragraph shall also apply.</p>
        <p>(k) Limited certification of nondestructive examination personnel who do not perform all of the operations of a nondestructive method that consists of more than one operation, or who perform nondestructive examinations of limited scope, may be based on fewer hours of training and experience than recommended in SNT-TC-1A or CP-189. Any limitations or restrictions placed upon a person's certification shall be described in the written practice and on the certification.</p>
        <p>(l) Either U.S. Customary Units or SI Units may be used for compliance with all requirements of this edition, but one system shall be used consistently throughout for all phases of construction.</p>
        <p>(1) Either the U.S. Customary Units or SI Units that are listed in Section V Mandatory Appendix II (in the rear of Section V and listed in other Code books) are identified in the text, or are identified in the nomenclature for equations shall be used consistently for all phases of construction (e.g., materials, design, fabrication, and reports). Since values in the two systems are not exact equivalents, each system shall be used independently of the other without mixing U.S. Customary Units and SI Units.</p>
        <p>(2) When SI Units are selected, U.S. Customary values in referenced specifications that do not contain SI Units shall be converted to SI values to at least three significant figures for use in calculations and other aspects of construction.</p>
    </div>
    <div class="subsection">
        <h4>T-130 EQUIPMENT</h4>
        <p>It is the responsibility of the Code User to ensure that the examination equipment being used conforms to the requirements of this Code Section.</p>
    </div>
    <div class="subsection">
        <h4>T-150 PROCEDURE</h4>
        <p>(a) When required by the referencing Code Section, all nondestructive examinations performed under this Code Section shall be performed following a written procedure.</p>
        <p>(1) The examination procedure shall comply with the applicable requirements of this Section for the particular examination method. A copy of each procedure shall be readily available to the NDE personnel for their reference and, upon request, to the Inspector.</p>
        <p>(2) The Inspector shall be satisfied with the capability of a procedure to detect relevant discontinuities by its application in a demonstration examination on a sample with at least one known discontinuity, except where otherwise specified by the referencing Code Section. When required by the referencing Code Section, a personnel demonstration may be used to verify the ability of the examiner to apply the examination procedure.</p>
        <p>(b) The nondestructive examination methods and techniques included in this Section are applicable to most geometric configurations and materials encountered in fabrication under normal conditions. Whenever special configurations or materials require modified methods and techniques, the organization shall develop special procedures which are equivalent or superior to the methods and techniques described in this Code Section, and which are capable of producing interpretable examination results under the special conditions. Such special procedures may be modifications or combinations of methods described or referenced in this Code Section. A procedure demonstration shall be performed on a sample with at least one known discontinuity, or by other means acceptable to the referencing Code Section and to the Inspector. This will verify the technique is capable of detecting discontinuities under the special conditions equal to the capabilities of the method when used under more general conditions. These special procedures shall be submitted to the Inspector for acceptance when required by the referencing Code Section, and shall be adopted as part of the Manufacturer's quality control program.</p>
        <p>(c) When a referencing Code Section requires an examination to be performed in accordance with the requirements of this Section, it shall be the responsibility of the organization to establish nondestructive examination procedures and personnel qualification and certification procedures conforming to the referenced requirements.</p>
        <p>(d) When qualification of the written examination procedure is required by the referencing Code Section, a qualification demonstration shall be performed prior to acceptance of production examinations. The qualification demonstration shall be performed</p>
        <p>(1) under the control and supervision of a Level III Examiner who is qualified and certified for performing the examination method and technique specified by the procedure, and shall be witnessed by the Inspector. The supervising Level III may be an employee of the qualifying organization or a subcontractor organization.</p>
        <p>(2) on a minimum of one test specimen having flaws whose size, location, orientation, quantity, and characterization have been determined prior to the demonstration and are known only by the supervising Level III Examiner.</p>
        <p>(-a) The maximum acceptable flaw size, required flaw orientation, and minimum number of flaws shall be as specified by the referencing Code Section.</p>
        <p>(-b) Natural flaws are preferred over artificial flaws whenever possible.</p>
        <p>(3) by a Level II or Level III Examiner (other than the supervising Level III) who is qualified and certified to perform the examination method and technique specified by the written procedure.</p>
        <p>The procedure shall be considered qualified when the supervising Level III and the Inspector are satisfied that indications produced by the demonstrated procedure reveal the size, location, orientation, quantity, and characterization of the flaws known to be present in the examined test specimen.</p>
        <p>The qualification demonstration shall be documented as required by the referencing Code Section and by this Section, as set forth in the applicable Article for the examination method and the applicable Appendix for the specified examination technique. The qualification document shall be annotated to indicate qualification of the written procedure, and identify the examined test specimen. The name and/or identity and signature of the supervising Level III and the witnessing Inspector shall be added to indicate their acceptance of the procedure qualification.</p>
    </div>
    <div class="subsection">
        <h4>T-160 CALIBRATION</h4>
        <p>(a) The organization shall assure that all equipment calibrations required by Subsection A and/or Subsection B are performed.</p>
        <p>(b) When special procedures are developed [see T-150(b)], the Code User shall specify what calibration is necessary, when calibration is required.</p>
    </div>
    <div class="subsection">
        <h4>T-170 EXAMINATIONS AND INSPECTIONS</h4>
        <p>(a) The Inspector concerned with the fabrication of the vessel or pressure part shall have the duty of verifying to the Inspector's satisfaction that all examinations required by the referencing Code Section have been made to the requirements of this Section and the referencing document(s). The Inspector shall have the right to witness any of these examinations to the extent stated in the referencing document(s). Throughout this Section of the Code, the word Inspector shall be as defined and qualified as required by the referencing Code Section or referencing document(s).</p>
        <p>(b) The special distinction established in the various Code Sections between inspection and examination and the personnel performing them is also adopted in this Code Section. In other words, the term inspection applies to the functions performed by the Inspector, but the term examination applies to those quality control functions performed by personnel employed by the organization. One area of occasional deviation from these distinctions exists. In the ASTM Standard Methods and Recommended Practices incorporated in this Section of the Code by reference or by reproduction in Subsection B, the words inspection or Inspector, which frequently occur in the text or titles of the referenced ASTM documents, may actually describe what the Code calls examination or examiner. This situation exists because ASTM has no occasion to be concerned with the distinctions which the Code makes between inspection and examination, since ASTM activities and documents do not involve the Inspector described in the Code Sections. However, no attempt has been made to edit the ASTM documents to conform with Code usage; this should cause no difficulty if the users of this Section recognize that the terms inspection, testing, and examination in the ASTM documents referenced in Subsection B do not describe duties of the Inspector but rather describe the things to be done by the organization's examination personnel.</p>
    </div>
    <div class="subsection">
        <h4>T-180 EVALUATION</h4>
        <p>The acceptance criteria for the NDE methods in this Section shall be as stated in the referencing Code Section, and where provided in the Articles of this Section. Acceptance criteria in the referencing Code Section shall take precedence.</p>
    </div>
    <div class="subsection">
        <h4>T-190 RECORDS/DOCUMENTATION</h4>
        <p>(a) Documentation and records shall be prepared as specified by the referencing Code Section and the applicable requirements of this Section. Examination records shall include the following information as a minimum:</p>
        <p>(1) date of the examination</p>
        <p>(2) name and/or identity and certification level (if applicable) for personnel performing the examination</p>
        <p>(3) identification of the weld, part, or component examined including weld number, serial number, or other identifier</p>
        <p>(4) examination method, technique, procedure identification, and revision</p>
        <p>(5) results of the examination</p>
        <p>(b) Personnel qualification and procedure performance demonstrations performed in compliance with the requirements of T-150(a) or T-150(b) shall be documented as specified by the referencing Code Section.</p>
        <p>(c) When documentation requirements for personnel qualification and procedure performance demonstrations performed in compliance with the requirements of T-150(a) or T-150(b) are not specified by the referencing Code Section, the following information shall be recorded as a minimum:</p>
        <p>(1) name of organization responsible for preparation and approval of the examination procedure</p>
        <p>(2) examination method applied</p>
        <p>(3) procedure number or designation</p>
        <p>(4) number and date of most recent revision</p>
        <p>(5) date of the demonstration</p>
        <p>(6) name and/or identity and certification level (if applicable) of personnel performing demonstration</p>
        <p>(d) Retention of examination records and related documentation (e.g., radiographs and review forms, ultrasonic scan files, etc.) shall be as specified by the referencing Code Section.</p>
        <p>(e) Digital images and reviewing software shall be retained under an appropriate record retention system that is capable of securely storing and retrieving data for the time period specified by the referencing Code Section.</p>
    </div>
    `,
    contentEs: `<h3>ARTÍCULO 1 REQUISITOS GENERALES</h3>
    <div class="subsection">
        <h4>T-110 ALCANCE</h4>
        <p>(a) Esta Sección del Código contiene requisitos, métodos y técnicas para el examen no destructivo (NDE), que son requisitos del Código en la medida en que sean específicamente referenciados y requeridos por otras Secciones del Código o documentos de referencia. Estos métodos NDE están destinados a detectar imperfecciones superficiales e internas en materiales, soldaduras, partes fabricadas y componentes. El Apéndice No Obligatorio A de este Artículo proporciona una lista de imperfecciones comunes y mecanismos de daño, y los métodos NDE que generalmente son capaces de detectarlos.</p>
        <p>(b) Para términos generales como inspección, defecto, discontinuidad, evaluación, etc., consulte el Apéndice Obligatorio I.</p>
        <p>(c) Las nuevas ediciones de la Sección V pueden usarse a partir de la fecha de emisión y se vuelven obligatorias 6 meses después de la fecha de emisión, a menos que sean modificadas por el documento de referencia.</p>
        <p>(d) Los Casos del Código son permisibles y pueden usarse, a partir de la fecha de aprobación por ASME. Solo pueden usarse los Casos del Código que estén específicamente identificados como aplicables a esta Sección. En el momento en que se aplica un Caso del Código, solo puede usarse la última revisión. Los Casos del Código que han sido incorporados a esta Sección o que han sido anulados no deberán usarse, a menos que lo permita el Código de referencia. Las calificaciones utilizando las disposiciones de un Caso del Código siguen siendo válidas después de que el Caso del Código sea anulado. El número del Caso del Código deberá figurar en el Procedimiento NDE o en la Certificación del Personal, según corresponda.</p>
    </div>
    <div class="subsection">
        <h4>T-120 GENERAL</h4>
        <p>(a) La Subsección A describe los métodos de examen no destructivo que se utilizarán si son referenciados por otras Secciones del Código o documentos de referencia.</p>
        <p>(b) La Subsección B enumera Estándares que cubren métodos de examen no destructivo que han sido aceptados como estándares. Estos estándares no son obligatorios a menos que sean específicamente referenciados en todo o en parte en la Subsección A o como se indica en otras Secciones del Código o documentos de referencia. Cuando haya un conflicto entre la Subsección A y la Subsección B, los requisitos de la Subsección A tendrán prioridad.</p>
        <p>(c) Cualquier referencia a un párrafo de cualquier Artículo en la Subsección A de esta Sección incluye todas las reglas aplicables en el párrafo. En todos los casos, la referencia a un párrafo incluye todos los subpárrafos y subdivisiones bajo ese párrafo.</p>
        <p>NOTA: Por ejemplo, una referencia a T-270 incluye todas las reglas contenidas en T-271 a T-277.3.</p>
        <p>(d) La referencia a un estándar contenido en la Subsección B es obligatoria solo en la medida especificada.</p>
        <p>NOTA: Por ejemplo, T-233 requiere que los Indicadores de Calidad de Imagen se fabriquen e identifiquen de acuerdo con los requisitos o alternativas permitidas en SE-747 o SE-1025, y Apéndices, según corresponda para el estilo de IQI que se utilizará. Estas son las únicas partes de SE-747 o SE-1025 que son obligatorias en el Artículo 2. En muchos casos, los documentos de la Subsección B no son obligatorios y están destinados solo para orientación o uso de referencia.</p>
        <p>(e) Para aquellos documentos que hacen referencia directa a este Artículo para la calificación del personal NDE, la calificación deberá realizarse de acuerdo con la práctica escrita de su empleador. Esta práctica escrita deberá abordar los métodos y técnicas que son aplicables a las operaciones de la organización y deberá estar de acuerdo con uno de los siguientes documentos:</p>
        <p>(1) SNT-TC-1A (Edición 2020),<sup>1</sup> Calificación y Certificación de Personal en Ensayos No Destructivos, con las siguientes excepciones:</p>
        <p>(-a) SNT-TC-1A (Edición 2020) no deberá considerarse una práctica recomendada sino que deberá proporcionar requisitos obligatorios. El verbo "shall" deberá usarse en lugar de "should" al establecer los requisitos mínimos de la práctica escrita.</p>
        <p>(-b) Las disposiciones del párrafo 1.5 no son aplicables a exámenes específicos y prácticos [véase (f) para las reglas relativas a los programas de certificación central].</p>
        <p>(-c) Los problemas de máquina son específicos del análisis de vibración y no son aplicables a los exámenes prácticos NDE.</p>
        <p>(-d) La evaluación del rendimiento técnico descrita en el párrafo 10.2 será obligatoria antes de la recertificación del personal Nivel I y Nivel II.</p>
        <p>(-e) Además de los requisitos de examen del párrafo 8.7, se requerirá que el personal NDT Nivel III prepare un procedimiento escrito para cada método aplicable, que cumpla con los requisitos de un código de construcción ASME o un código o estándar de inspección en servicio relacionado antes de la certificación inicial por cada empleador. Para las personas actualmente certificadas, el requisito del procedimiento deberá cumplirse en el próximo evento de recertificación. La evaluación del procedimiento se realizará utilizando una lista de verificación escrita que aborde elementos relacionados con la adecuación técnica y práctica del procedimiento NDE. Se requiere una calificación mínima aprobatoria del 80%. La evaluación del procedimiento será realizada por el NDT Nivel III responsable del método aplicable y así registrado.</p>
        <p>(-1) Si el candidato a NDT Nivel III será requerido para administrar exámenes prácticos para certificación o para realizar exámenes, interpretaciones o evaluaciones según un código o estándar ASME, el candidato deberá completar los exámenes prácticos requeridos para un Nivel II en cada técnica aplicable dentro del método con su empleador actual.</p>
        <p>(-2) La calificación compuesta para el personal NDT Nivel III se determinará mediante el promedio simple de cada examen requerido, incluyendo el procedimiento escrito y el examen práctico, según corresponda, y así registrado. Se requiere una calificación compuesta de al menos el 80%.</p>
        <p>(-3) El candidato a NDT Nivel III deberá completar los requisitos de (-e) solo una vez para el empleador actual. El personal NDT Nivel III no está obligado a completar los requisitos de (-e) para la recertificación.</p>
        <p>(2) ANSI/ASNT CP-189 (Edición 2020),<sup>1</sup> Estándar ASNT para la Calificación y Certificación de Personal de Ensayos No Destructivos, excepto que las disposiciones del párrafo 1.5 no son aplicables a exámenes específicos y prácticos [véase (f) para las reglas relativas a los programas de certificación central].</p>
        <p>(f) Los programas nacionales o internacionales de certificación central, como los programas basados en ISO 9712, pueden usarse alternativamente para cumplir con los requisitos de práctica escrita de (e) para capacitación, experiencia, examen general, examen básico y examen de método, según corresponda.</p>
        <p>(g) Además de los requisitos descritos en (e) o (f) anteriores, si se van a utilizar las técnicas de radiografía computarizada (CR), radiografía digital (DR), ultrasónico de matriz faseada (PAUT), ultrasónico de difracción de tiempo de vuelo (TOFD) o ultrasonido de captura de matriz completa (FMC), los requisitos de capacitación, experiencia y examen que se encuentran en el Artículo 1, Apéndice Obligatorio II también deberán incluirse en la práctica escrita del empleador para cada técnica según corresponda.</p>
        <p>(h) Alternativamente, los programas de calificación basados en el rendimiento, de acuerdo con ASME ANDE-1-2020, Programa de Calificación y Certificación Central de Examen No Destructivo y Control de Calidad de ASME, pueden usarse para actividades de capacitación, experiencia, examen y certificación según se especifica en la práctica escrita.</p>
        <p>(i) Cuando la Sección del Código de referencia no especifica calificaciones o no hace referencia directa al Artículo 1 de esta Sección, la calificación puede implicar simplemente una demostración para mostrar que el personal que realiza los exámenes no destructivos es competente para hacerlo de acuerdo con los procedimientos establecidos de la organización.</p>
        <p>(j) El usuario de este Artículo es responsable de la calificación y certificación del personal NDE de acuerdo con los requisitos de este Artículo. El Programa de Calidad de la organización<sup>2</sup> deberá estipular cómo se debe lograr esto. Las calificaciones de acuerdo con una edición anterior de esta Sección son válidas hasta la recertificación. La recertificación o nueva certificación deberá realizarse de acuerdo con la edición actual de esta Sección. Cuando se utilicen cualquiera de las técnicas incluidas en (g) anterior, también se aplicarán los requisitos adicionales de ese párrafo.</p>
        <p>(k) La certificación limitada del personal de examen no destructivo que no realiza todas las operaciones de un método no destructivo que consiste en más de una operación, o que realiza exámenes no destructivos de alcance limitado, puede basarse en menos horas de capacitación y experiencia que las recomendadas en SNT-TC-1A o CP-189. Cualquier limitación o restricción impuesta a la certificación de una persona deberá describirse en la práctica escrita y en la certificación.</p>
        <p>(l) Pueden usarse las Unidades Consuetudinarias de EE.UU. o las Unidades SI para el cumplimiento con todos los requisitos de esta edición, pero un sistema deberá usarse consistentemente en todas las fases de la construcción.</p>
        <p>(1) Las Unidades Consuetudinarias de EE.UU. o las Unidades SI que figuran en el Apéndice Obligatorio II de la Sección V (al final de la Sección V y enumeradas en otros libros del Código) que están identificadas en el texto, o que están identificadas en la nomenclatura de las ecuaciones, deberán usarse consistentemente para todas las fases de la construcción (por ejemplo, materiales, diseño, fabricación e informes). Dado que los valores en los dos sistemas no son equivalentes exactos, cada sistema deberá usarse independientemente del otro sin mezclar Unidades Consuetudinarias de EE.UU. y Unidades SI.</p>
        <p>(2) Cuando se seleccionan las Unidades SI, los valores en Unidades Consuetudinarias de EE.UU. en especificaciones de referencia que no contienen Unidades SI deberán convertirse a valores SI con al menos tres cifras significativas para su uso en cálculos y otros aspectos de la construcción.</p>
    </div>
    <div class="subsection">
        <h4>T-130 EQUIPO</h4>
        <p>Es responsabilidad del Usuario del Código garantizar que el equipo de examen que se está utilizando cumpla con los requisitos de esta Sección del Código.</p>
    </div>
    <div class="subsection">
        <h4>T-150 PROCEDIMIENTO</h4>
        <p>(a) Cuando lo requiera la Sección del Código de referencia, todos los exámenes no destructivos realizados bajo esta Sección del Código deberán realizarse siguiendo un procedimiento escrito.</p>
        <p>(1) El procedimiento de examen deberá cumplir con los requisitos aplicables de esta Sección para el método de examen particular. Una copia de cada procedimiento deberá estar fácilmente disponible para el personal NDE para su referencia y, a solicitud, para el Inspector.</p>
        <p>(2) El Inspector deberá quedar satisfecho con la capacidad de un procedimiento para detectar discontinuidades relevantes mediante su aplicación en un examen de demostración en una muestra con al menos una discontinuidad conocida, excepto donde se especifique lo contrario por la Sección del Código de referencia. Cuando lo requiera la Sección del Código de referencia, puede usarse una demostración de personal para verificar la capacidad del examinador para aplicar el procedimiento de examen.</p>
        <p>(b) Los métodos y técnicas de examen no destructivo incluidos en esta Sección son aplicables a la mayoría de las configuraciones geométricas y materiales encontrados en la fabricación bajo condiciones normales. Siempre que configuraciones o materiales especiales requieran métodos y técnicas modificados, la organización deberá desarrollar procedimientos especiales que sean equivalentes o superiores a los métodos y técnicas descritos en esta Sección del Código, y que sean capaces de producir resultados de examen interpretables bajo las condiciones especiales. Dichos procedimientos especiales pueden ser modificaciones o combinaciones de métodos descritos o referenciados en esta Sección del Código. Se deberá realizar una demostración del procedimiento en una muestra con al menos una discontinuidad conocida, o por otros medios aceptables para la Sección del Código de referencia y para el Inspector. Esto verificará que la técnica es capaz de detectar discontinuidades bajo las condiciones especiales iguales a las capacidades del método cuando se usa bajo condiciones más generales. Estos procedimientos especiales deberán someterse al Inspector para su aceptación cuando lo requiera la Sección del Código de referencia, y deberán adoptarse como parte del programa de control de calidad del Fabricante.</p>
        <p>(c) Cuando una Sección del Código de referencia requiera que un examen se realice de acuerdo con los requisitos de esta Sección, será responsabilidad de la organización establecer procedimientos de examen no destructivo y procedimientos de calificación y certificación de personal que cumplan con los requisitos de referencia.</p>
        <p>(d) Cuando la calificación del procedimiento de examen escrito sea requerida por la Sección del Código de referencia, se deberá realizar una demostración de calificación antes de la aceptación de los exámenes de producción. La demostración de calificación deberá realizarse</p>
        <p>(1) bajo el control y supervisión de un Examinador Nivel III que esté calificado y certificado para realizar el método y técnica de examen especificados por el procedimiento, y deberá ser presenciada por el Inspector. El Supervisor Nivel III puede ser un empleado de la organización calificadora o una organización subcontratista.</p>
        <p>(2) en un mínimo de un espécimen de prueba que tenga defectos cuyo tamaño, ubicación, orientación, cantidad y caracterización hayan sido determinados antes de la demostración y sean conocidos solo por el Examinador Supervisor Nivel III.</p>
        <p>(-a) El tamaño máximo aceptable del defecto, la orientación requerida del defecto y el número mínimo de defectos serán los especificados por la Sección del Código de referencia.</p>
        <p>(-b) Se prefieren los defectos naturales sobre los defectos artificiales siempre que sea posible.</p>
        <p>(3) por un Examinador Nivel II o Nivel III (que no sea el Supervisor Nivel III) que esté calificado y certificado para realizar el método y técnica de examen especificados por el procedimiento escrito.</p>
        <p>El procedimiento se considerará calificado cuando el Supervisor Nivel III y el Inspector estén satisfechos de que las indicaciones producidas por el procedimiento demostrado revelen el tamaño, ubicación, orientación, cantidad y caracterización de los defectos conocidos presentes en el espécimen de prueba examinado.</p>
        <p>La demostración de calificación deberá documentarse según lo requerido por la Sección del Código de referencia y por esta Sección, según lo establecido en el Artículo aplicable para el método de examen y el Apéndice aplicable para la técnica de examen especificada. El documento de calificación deberá anotarse para indicar la calificación del procedimiento escrito, e identificar el espécimen de prueba examinado. El nombre y/o identidad y firma del Supervisor Nivel III y del Inspector testigo deberán añadirse para indicar su aceptación de la calificación del procedimiento.</p>
    </div>
    <div class="subsection">
        <h4>T-160 CALIBRACIÓN</h4>
        <p>(a) La organización deberá asegurar que se realicen todas las calibraciones de equipo requeridas por la Subsección A y/o la Subsección B.</p>
        <p>(b) Cuando se desarrollen procedimientos especiales [véase T-150(b)], el Usuario del Código deberá especificar qué calibración es necesaria, cuándo se requiere la calibración.</p>
    </div>
    <div class="subsection">
        <h4>T-170 EXÁMENES E INSPECCIONES</h4>
        <p>(a) El Inspector encargado de la fabricación del recipiente o parte a presión tendrá el deber de verificar, a satisfacción del Inspector, que todos los exámenes requeridos por la Sección del Código de referencia se hayan realizado de acuerdo con los requisitos de esta Sección y los documentos de referencia. El Inspector tendrá el derecho de presenciar cualquiera de estos exámenes en la medida indicada en los documentos de referencia. A lo largo de esta Sección del Código, la palabra Inspector deberá ser como se define y califica según lo requerido por la Sección del Código de referencia o los documentos de referencia.</p>
        <p>(b) La distinción especial establecida en las diversas Secciones del Código entre inspección y examen y el personal que los realiza también se adopta en esta Sección del Código. En otras palabras, el término inspección se aplica a las funciones realizadas por el Inspector, pero el término examen se aplica a esas funciones de control de calidad realizadas por personal empleado por la organización. Existe un área de desviación ocasional de estas distinciones. En los Métodos Estándar y Prácticas Recomendadas de ASTM incorporados en esta Sección del Código por referencia o por reproducción en la Subsección B, las palabras inspección o Inspector, que aparecen frecuentemente en el texto o títulos de los documentos ASTM referenciados, pueden describir en realidad lo que el Código llama examen o examinador. Esta situación existe porque ASTM no tiene ocasión de preocuparse por las distinciones que el Código hace entre inspección y examen, ya que las actividades y documentos de ASTM no involucran al Inspector descrito en las Secciones del Código. Sin embargo, no se ha hecho ningún intento de editar los documentos ASTM para que se ajusten al uso del Código; esto no debería causar dificultad si los usuarios de esta Sección reconocen que los términos inspección, prueba y examen en los documentos ASTM referenciados en la Subsección B no describen deberes del Inspector sino que describen las cosas que deben ser hechas por el personal de examen de la organización.</p>
    </div>
    <div class="subsection">
        <h4>T-180 EVALUACIÓN</h4>
        <p>Los criterios de aceptación para los métodos NDE en esta Sección serán los establecidos en la Sección del Código de referencia, y donde se proporcionen en los Artículos de esta Sección. Los criterios de aceptación en la Sección del Código de referencia tendrán prioridad.</p>
    </div>
    <div class="subsection">
        <h4>T-190 REGISTROS/DOCUMENTACIÓN</h4>
        <p>(a) La documentación y los registros deberán prepararse según lo especificado por la Sección del Código de referencia y los requisitos aplicables de esta Sección. Los registros de examen deberán incluir la siguiente información como mínimo:</p>
        <p>(1) fecha del examen</p>
        <p>(2) nombre y/o identidad y nivel de certificación (si es aplicable) del personal que realiza el examen</p>
        <p>(3) identificación de la soldadura, parte o componente examinado, incluyendo número de soldadura, número de serie u otro identificador</p>
        <p>(4) método de examen, técnica, identificación del procedimiento y revisión</p>
        <p>(5) resultados del examen</p>
        <p>(b) La calificación del personal y las demostraciones de rendimiento del procedimiento realizadas de acuerdo con los requisitos de T-150(a) o T-150(b) deberán documentarse según lo especificado por la Sección del Código de referencia.</p>
        <p>(c) Cuando los requisitos de documentación para la calificación del personal y las demostraciones de rendimiento del procedimiento realizadas de acuerdo con los requisitos de T-150(a) o T-150(b) no estén especificados por la Sección del Código de referencia, deberá registrarse la siguiente información como mínimo:</p>
        <p>(1) nombre de la organización responsable de la preparación y aprobación del procedimiento de examen</p>
        <p>(2) método de examen aplicado</p>
        <p>(3) número o designación del procedimiento</p>
        <p>(4) número y fecha de la revisión más reciente</p>
        <p>(5) fecha de la demostración</p>
        <p>(6) nombre y/o identidad y nivel de certificación (si es aplicable) del personal que realiza la demostración</p>
        <p>(d) La retención de los registros de examen y la documentación relacionada (por ejemplo, radiografías y formularios de revisión, archivos de escaneo ultrasónico, etc.) será según lo especificado por la Sección del Código de referencia.</p>
        <p>(e) Las imágenes digitales y el software de revisión deberán conservarse bajo un sistema de retención de registros adecuado que sea capaz de almacenar y recuperar datos de forma segura durante el período de tiempo especificado por la Sección del Código de referencia.</p>
    </div>
    `
});