// Registrar el código API 578 si no existe
if (!getCode('API578')) {
    console.error('El código API 578 no está registrado. Registrándolo ahora...');
    registerCode('API578', {
        title: "API 578 Material Verification Program for New and Existing Alloy Piping Systems",
        titleEs: "API 578 Programa de Verificación de Materiales para Sistemas de Tuberías de Aleación Nuevos y Existentes"
    });
}

// Registrar el Anexo A
registerChapter('API578', {
    id: 'A',
    title: "Statistical Terminology",
    titleEs: "Terminología Estadística",
    content: `<h3>Annex A</h3>
    <h4>(informative)</h4>
    <h3>Statistical Terminology</h3>
    <div class="subsection">
        <p>Below are some of the terms regarding statistics that may be encountered when using the methodology and/or technology discussed within this document. PMI inspectors should understand the listed terms to properly appreciate what each of the analyzer types (XRF, OES, LIBS) is capable of measuring to produce accurate results. Understanding these will help the PMI inspectors accomplish their goals in performing PMI for the owner user's MVP.</p>
        
        <div class="definition-item">
            <strong>Accuracy</strong>
            <p>The closeness of agreement between the test result and the accepted reference value.</p>
        </div>
        
        <div class="definition-item">
            <strong>Precision</strong>
            <p>The closeness of agreement between independent test results. The precision depends only on the distribution of random errors and does not relate to the accepted standard certified value.</p>
        </div>
        
        <div class="figure-container">
            <img src="images/api578_figure_a1.png" class="figure-image">
            <p class="figure-caption">Figure A.1—Illustration of Statistical Accuracy</p>
        </div>
        
        <div class="definition-item">
            <strong>Bias</strong>
            <p>The difference between the expectation of the test results and an accepted reference value. Bias is a systematic error, in contrast to a random error. There may be one or more systematic error components contributing to the bias.</p>
        </div>
        
        <div class="definition-item">
            <strong>Limit of detection (LOD)</strong>
            <p>The lowest concentration of analyte that can be reliably distinguished from zero concentration in a sample by defining a 99 % confidence to show that the analyte concentration is greater than zero. Therefore, 3-sigma calculations must be used to determine LOD (see definition for standard deviation below).</p>
        </div>
        
        <div class="definition-item">
            <strong>Instrument detection limit (IDL)</strong>
            <p>The lowest (best) detection limit generated by an instrument in a clean matrix (blank).</p>
        </div>
        
        <div class="definition-item">
            <strong>Method detection limit (MDL)</strong>
            <p>The typical detection limit obtained when running a typical sample. It is matrix dependent and will vary from matrix to matrix.</p>
        </div>
        
        <div class="definition-item">
            <strong>Limit of quantitation (LOQ)</strong>
            <p>The lowest concentration that can be reliably measured to allow quantitative readings. It is typically defined as 10-sigma (or 3.33 times the LOD).</p>
        </div>
        
        <div class="definition-item">
            <strong>Standard deviation (SD)</strong>
            <p>The standard deviation is a statistic that defines how tightly all the data are clustered around the mean in a data set. It essentially measures the variability (spread or dispersion) from the mean (average) and is defined mathematically. For "normal" distributions, we can apply an empirical rule that states that 68 % of the data are within one standard deviation of the mean; 95 % of the data are within two standard deviations of the mean; and 99.7 % of the data are within three standard deviations of the mean.</p>
        </div>
        
        <div class="definition-item">
            <strong>Relative standard deviation</strong>
            <p>The standard deviation is divided by the mean of the data and multiplied by 100 to give a % value. The bigger the % value, the "noisier" the signal and less confidence in the final value.</p>
        </div>
        
        <div class="definition-item">
            <strong>Repeatability</strong>
            <p>The duplicate (or more) analysis within the shortest possible time, performed by the same person using the same method. The standard of many analyses using repeatability conditions indicates the minimum deviation achievable in the particular conditions.</p>
        </div>
        
        <div class="definition-item">
            <strong>Reproducibility</strong>
            <p>This is a duplicate (or more) analysis performed by a different person, preferably using a different method or different instrument.</p>
        </div>
    </div>`,
    contentEs: `<h3>Anexo A</h3>
    <h4>(informativo)</h4>
    <h3>Terminología Estadística</h3>
    <div class="subsection">
        <p>A continuación se presentan algunos de los términos relacionados con estadística que pueden encontrarse al utilizar la metodología y/o tecnología discutida en este documento. Los inspectores de PMI deben comprender los términos listados para apreciar adecuadamente lo que cada tipo de analizador (XRF, OES, LIBS) es capaz de medir para producir resultados precisos. Comprender estos términos ayudará a los inspectores de PMI a lograr sus objetivos en la realización de PMI para el MVP del propietario/usuario.</p>
        
        <div class="definition-item">
            <strong>Precisión (Accuracy)</strong>
            <p>La cercanía del acuerdo entre el resultado de la prueba y el valor de referencia aceptado.</p>
        </div>
        
        <div class="definition-item">
            <strong>Exactitud (Precision)</strong>
            <p>La cercanía del acuerdo entre resultados de prueba independientes. La exactitud depende solo de la distribución de errores aleatorios y no se relaciona con el valor certificado del estándar aceptado.</p>
        </div>
        
        <div class="figure-container">
        <img src="images/api578_figure_a1.png" class="figure-image">
            <p class="figure-caption">Figura A.1—Ilustración de Precisión Estadística</p>
        </div>
        
        <div class="definition-item">
            <strong>Sesgo (Bias)</strong>
            <p>La diferencia entre la expectativa de los resultados de prueba y un valor de referencia aceptado. El sesgo es un error sistemático, en contraste con un error aleatorio. Puede haber uno o más componentes de error sistemático que contribuyan al sesgo.</p>
        </div>
        
        <div class="definition-item">
            <strong>Límite de detección (LOD)</strong>
            <p>La concentración más baja de analito que puede distinguirse de manera confiable de la concentración cero en una muestra definiendo un 99 % de confianza para mostrar que la concentración de analito es mayor que cero. Por lo tanto, deben usarse cálculos de 3-sigma para determinar el LOD (ver definición de desviación estándar a continuación).</p>
        </div>
        
        <div class="definition-item">
            <strong>Límite de detección del instrumento (IDL)</strong>
            <p>El límite de detección más bajo (mejor) generado por un instrumento en una matriz limpia (blanco).</p>
        </div>
        
        <div class="definition-item">
            <strong>Límite de detección del método (MDL)</strong>
            <p>El límite de detección típico obtenido al ejecutar una muestra típica. Es dependiente de la matriz y variará de una matriz a otra.</p>
        </div>
        
        <div class="definition-item">
            <strong>Límite de cuantificación (LOQ)</strong>
            <p>La concentración más baja que puede medirse de manera confiable para permitir lecturas cuantitativas. Típicamente se define como 10-sigma (o 3.33 veces el LOD).</p>
        </div>
        
        <div class="definition-item">
            <strong>Desviación estándar (SD)</strong>
            <p>La desviación estándar es una estadística que define qué tan estrechamente todos los datos están agrupados alrededor de la media en un conjunto de datos. Esencialmente mide la variabilidad (dispersión) desde la media (promedio) y se define matemáticamente. Para distribuciones "normales", podemos aplicar una regla empírica que establece que el 68 % de los datos están dentro de una desviación estándar de la media; el 95 % de los datos están dentro de dos desviaciones estándar de la media; y el 99.7 % de los datos están dentro de tres desviaciones estándar de la media.</p>
        </div>
        
        <div class="definition-item">
            <strong>Desviación estándar relativa</strong>
            <p>La desviación estándar se divide por la media de los datos y se multiplica por 100 para dar un valor porcentual. Cuanto mayor sea el valor porcentual, más "ruidoso" será la señal y menor confianza en el valor final.</p>
        </div>
        
        <div class="definition-item">
            <strong>Repetibilidad</strong>
            <p>El análisis duplicado (o más) en el tiempo más corto posible, realizado por la misma persona utilizando el mismo método. El estándar de muchos análisis utilizando condiciones de repetibilidad indica la desviación mínima alcanzable en las condiciones particulares.</p>
        </div>
        
        <div class="definition-item">
            <strong>Reproducibilidad</strong>
            <p>Este es un análisis duplicado (o más) realizado por una persona diferente, preferiblemente utilizando un método diferente o instrumento diferente.</p>
        </div>
    </div>`
});